
name = "jsonf"
version = "0.1.0"
license = "BSD 3-Clause"
author = "Jeff Irwin"
maintainer = "jirwin505@gmail.com"
copyright = "Copyright 2025, Jeff Irwin"

[[executable]]
name = "jsonf"
source-dir = "app"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = true

[install]
library = false
test = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

