
name: ci

on: [push]

jobs:

  test-docker:
    name: Test in docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test in docker
      run: |
        git submodule update --init --recursive --depth 1
        docker build . -t rocky

